<a href="https://colab.research.google.com/github/keepertrainer78698/keeperstats/blob/main/Instat_XML_file_process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Process to work with Instat's xml file

## Import libraries

In [15]:
!pip install pandas_read_xml
!pip install -U pandasql
import pandas_read_xml as pdx 
from pandas_read_xml import flatten, fully_flatten, auto_separate_tables
import os,glob 
import pandas as pd
import time
import numpy as np
from pandasql import sqldf
from google.colab import drive

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas_read_xml in /usr/local/lib/python3.7/dist-packages (0.3.1)
Requirement already satisfied: zipfile36 in /usr/local/lib/python3.7/dist-packages (from pandas_read_xml) (0.1.3)
Requirement already satisfied: distlib in /usr/local/lib/python3.7/dist-packages (from pandas_read_xml) (0.3.4)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from pandas_read_xml) (2.28.1)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.7/dist-packages (from pandas_read_xml) (6.0.1)
Requirement already satisfied: xmltodict in /usr/local/lib/python3.7/dist-packages (from pandas_read_xml) (0.13.0)
Requirement already satisfied: urllib3>=1.26.3 in /usr/local/lib/python3.7/dist-packages (from pandas_read_xml) (1.26.10)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pandas_read_xml) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandas_read_xml) (2022.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandas_read_xml) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandas_read_xml) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->pandas_read_xml) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->pandas_read_xml) (2.10)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests->pandas_read_xml) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->pandas_read_xml) (2022.6.15)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandasql in /usr/local/lib/python3.7/dist-packages (0.7.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.4.37)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->pandasql) (1.15.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (4.11.4)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (1.1.2)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (3.8.0)

## Setup the name of the tournament

In [16]:
nombre_torneo = "La Liga"

## Setup the google drive folder's path
The idea is to download all the xml from Instat and put all in a google drive folder.

In [17]:
 #this is an example of my folder's path
 drive.mount('/content/drive')
 %cd /content/drive/MyDrive/instat/

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/instat

## Remove excel files from previous process
The script will generate an excel file for each xml, so the idea is to remove the files from previous process.

In [18]:
print('Finding and removing old excel files...')
excel_files = []
for file in glob.glob("*.xlsx"):
    excel_files.append(file)

for file in excel_files:
  os.remove(file)

print('done!')

Finding and removing old excel files...
done!

## Let's find all the XML files in the folder

In [19]:
print('Finding xml files...')
xml_files = []
for file in glob.glob("*.xml"):
    xml_files.append(file)

print('done!')

Finding xml files...
done!

## Generate an excel file for each xml file

In [20]:
print('Creating excel files from xmls')
open_file =""
for xml in xml_files:
  # This line will remove the name of the competion from the xml file name
  file_name = xml.replace('--Spain--Primera-Division','') # CHOOSE THE TEXT BETWEEN THE DATE AND THE FIRST TEAM NAME IN FILE NAME
  # This line will remove the text '.xml' from the variable 'file_name' 
  file_name = file_name.replace('.xml','')
  # This line will create a dataframe with the xml data
  open_file = pdx.read_xml(xml, ['file', 'ALL_INSTANCES', 'instance'], root_is_rows=False)
  # This line is to create a new column named 'file_name', the column will contain the information of the game
  open_file["file_name"] = file_name
  # This line will generate an excel file
  open_file.to_excel(file_name + ".xlsx")
  #print(open_file.file_name)

print('done!')
open_file

Creating excel files from xmls
done!

,ID,start,end,code,label,pos_x,pos_y,file_name
0,1,2.29,22.29,10. Iker Muniain,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",51.8,34.6,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
1,2,2.29,22.29,10. Iker Muniain,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",51.8,34.6,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
2,3,4.61,24.61,4. Inigo Martinez,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",33.4,45.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
3,4,4.61,24.61,4. Inigo Martinez,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",33.4,45.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
4,5,5.88,25.88,6. Mikel Vesga Arruti,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",44.9,45.9,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
...,...,...,...,...,...,...,...,...
3976,3977,5976.55,5996.55,10. Iker Muniain,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",69.6,24.2,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
3977,3978,5976.55,5996.55,10. Iker Muniain,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",69.6,24.2,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
3978,3979,5976.55,5996.55,10. Iker Muniain,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",69.6,24.2,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
3979,3980,5977.98,5997.98,1. Marko Dmitrovic,"[{'group': 'Team', 'text': 'Sevilla'}, {'group...",5.5,34.5,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
3980,3981,5977.98,5997.98,1. Marko Dmitrovic,"[{'group': 'Team', 'text': 'Sevilla'}, {'group...",5.5,34.5,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...

## Merge all excel files in one dataframe

In [21]:
print('Merging files...')
all_data = pd.DataFrame()
for f in glob.glob("*.xlsx"):
    df = pd.read_excel(f)
    all_data = all_data.append(df,ignore_index=True)
print('done!')
all_data

Merging files...
done!

,Unnamed: 0,ID,start,end,code,label,pos_x,pos_y,file_name
0,0,1,2.29,22.29,10. Iker Muniain,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",51.8,34.6,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
1,1,2,2.29,22.29,10. Iker Muniain,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",51.8,34.6,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
2,2,3,4.61,24.61,4. Inigo Martinez,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",33.4,45.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
3,3,4,4.61,24.61,4. Inigo Martinez,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",33.4,45.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
4,4,5,5.88,25.88,6. Mikel Vesga Arruti,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",44.9,45.9,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
...,...,...,...,...,...,...,...,...,...
3976,3976,3977,5976.55,5996.55,10. Iker Muniain,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",69.6,24.2,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
3977,3977,3978,5976.55,5996.55,10. Iker Muniain,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",69.6,24.2,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
3978,3978,3979,5976.55,5996.55,10. Iker Muniain,"[{'group': 'Team', 'text': 'Athletic Bilbao'},...",69.6,24.2,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
3979,3979,3980,5977.98,5997.98,1. Marko Dmitrovic,"[{'group': 'Team', 'text': 'Sevilla'}, {'group...",5.5,34.5,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...
3980,3980,3981,5977.98,5997.98,1. Marko Dmitrovic,"[{'group': 'Team', 'text': 'Sevilla'}, {'group...",5.5,34.5,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...

## Split column `'Label'` by comma `','`

In [22]:
#Create new dataframe with the new columns from the column 'LABEL'
print('Creating new data frame')
all_data2 = all_data['label'].str.split(',', expand=True)


#Merge original dataframe and new dataframe
print('Merging dataframes')
all_data = pd.concat([all_data, all_data2], axis=1, sort=False)

###REMOVE UNNCESSARY COLUMNS
print('Removing columns')
all_data.drop('label', inplace=True, axis=1)
all_data.drop(0, inplace=True, axis=1)
all_data.drop(2, inplace=True, axis=1)
all_data.drop(4, inplace=True, axis=1)

#### RENAME NEW COLUMNS (Teams, Actions, Time)
print('Reanaming columns')
all_data = all_data.rename(columns={1: "Equipos", 3: "Acciones",5:"Tiempo"})


#### REPLACE CHARACTERS IN COLUMNS EQUIPOS, ACCIONES, TIEMPO
print('Replacing special characters')
import re
chars_to_remove = ['.', '-', '(', ')',']','\'', '','}',':']
regular_expression = '[' + re.escape (''. join (chars_to_remove)) + ']'

all_data['Equipos'] = all_data['Equipos'].str.replace(regular_expression, '', regex=True)
all_data['Acciones'] = all_data['Acciones'].str.replace(regular_expression, '', regex=True)
all_data['Tiempo'] = all_data['Tiempo'].str.replace(regular_expression, '', regex=True)

all_data['Equipos'] = all_data['Equipos'].str.replace('text','')
all_data['Acciones'] = all_data['Acciones'].str.replace('text','')
all_data['Tiempo'] = all_data['Tiempo'].str.replace('text','')


print('done!')

Creating new data frame
Merging dataframes
Removing columns
Reanaming columns
Replacing special characters
done!

## Preview the dataframe

In [23]:
all_data.head(20)

,Unnamed: 0,ID,start,end,code,pos_x,pos_y,file_name,Equipos,Acciones,Tiempo
0,0,1,2.29,22.29,10. Iker Muniain,51.8,34.6,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Passes accurate,1st half
1,1,2,2.29,22.29,10. Iker Muniain,51.8,34.6,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Positional attacks,1st half
2,2,3,4.61,24.61,4. Inigo Martinez,33.4,45.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Positional attacks,1st half
3,3,4,4.61,24.61,4. Inigo Martinez,33.4,45.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Passes accurate,1st half
4,4,5,5.88,25.88,6. Mikel Vesga Arruti,44.9,45.9,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Positional attacks,1st half
5,5,6,5.88,25.88,6. Mikel Vesga Arruti,44.9,45.9,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Passes accurate,1st half
6,6,7,7.49,27.49,4. Inigo Martinez,30.1,46.7,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Positional attacks,1st half
7,7,8,7.49,27.49,4. Inigo Martinez,30.1,46.7,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Passes accurate,1st half
8,8,9,10.06,30.06,12. Daniel Vivian Moreno,27.3,24.3,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Positional attacks,1st half
9,9,10,10.06,30.06,12. Daniel Vivian Moreno,27.3,24.3,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Passes accurate,1st half
10,10,11,12.29,13.29,Start,NaN,NaN,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,NaN,NaN,NaN
11,11,12,12.38,32.38,18. De Marcos,35.0,4.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Positional attacks,1st half
12,12,13,14.07,34.07,18. De Marcos,30.0,4.6,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Positional attacks,1st half
13,13,14,14.07,34.07,18. De Marcos,30.0,4.6,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Passes accurate,1st half
14,14,15,14.81,34.81,12. Daniel Vivian Moreno,22.2,9.9,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Positional attacks,1st half
15,15,16,14.81,34.81,12. Daniel Vivian Moreno,22.2,9.9,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Athletic Bilbao,Passes inaccurate,1st half
16,16,17,17.36,37.36,20. Diego Carlos,32.7,51.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Sevilla,Positional attacks,1st half
17,17,18,17.36,37.36,20. Diego Carlos,32.7,51.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Sevilla,Positional attacks,1st half
18,18,19,17.36,37.36,20. Diego Carlos,32.7,51.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Sevilla,Passes inaccurate,1st half
19,19,20,17.36,37.36,20. Diego Carlos,32.7,51.4,22-05-2022Sevilla-1-0-Athletic-Bilbao20220629-...,Sevilla,Interceptions,1st half

## Get new columns from `file_name` column

In [24]:
#New column 'fecha_partido' (game_date)
print('creating new column fecha_partido')
all_data['fecha_partido'] = all_data['file_name'].str[:10]


#New column 'nombre_torneo' (tournament_name)
print('creating new column nombre_torneo')
all_data['nombre_torneo'] = nombre_torneo

#remove game date from string
print('Removing game date from string')
all_data['file_name'] = all_data['file_name'].str[10:]


#Remove last 20 characters
print('removing unnecessary last 22 last characters')
all_data['file_name'] = all_data['file_name'].str[:-20]

####RENAME COLUMN FILE_NAME
print('Reanaming column')
all_data = all_data.rename(columns={'file_name': "Partido"})

print('done!')

creating new column fecha_partido
creating new column nombre_torneo
Removing game date from string
removing unnecessary last 22 last characters
Reanaming column
done!

## Preview the dataframe with the new columns

In [25]:
all_data.head(20)

,Unnamed: 0,ID,start,end,code,pos_x,pos_y,Partido,Equipos,Acciones,Tiempo,fecha_partido,nombre_torneo
0,0,1,2.29,22.29,10. Iker Muniain,51.8,34.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga
1,1,2,2.29,22.29,10. Iker Muniain,51.8,34.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga
2,2,3,4.61,24.61,4. Inigo Martinez,33.4,45.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga
3,3,4,4.61,24.61,4. Inigo Martinez,33.4,45.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga
4,4,5,5.88,25.88,6. Mikel Vesga Arruti,44.9,45.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga
5,5,6,5.88,25.88,6. Mikel Vesga Arruti,44.9,45.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga
6,6,7,7.49,27.49,4. Inigo Martinez,30.1,46.7,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga
7,7,8,7.49,27.49,4. Inigo Martinez,30.1,46.7,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga
8,8,9,10.06,30.06,12. Daniel Vivian Moreno,27.3,24.3,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga
9,9,10,10.06,30.06,12. Daniel Vivian Moreno,27.3,24.3,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga
10,10,11,12.29,13.29,Start,NaN,NaN,Sevilla-1-0-Athletic-Bilbao,NaN,NaN,NaN,22-05-2022,La Liga
11,11,12,12.38,32.38,18. De Marcos,35.0,4.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga
12,12,13,14.07,34.07,18. De Marcos,30.0,4.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga
13,13,14,14.07,34.07,18. De Marcos,30.0,4.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga
14,14,15,14.81,34.81,12. Daniel Vivian Moreno,22.2,9.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga
15,15,16,14.81,34.81,12. Daniel Vivian Moreno,22.2,9.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes inaccurate,1st half,22-05-2022,La Liga
16,16,17,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Positional attacks,1st half,22-05-2022,La Liga
17,17,18,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Positional attacks,1st half,22-05-2022,La Liga
18,18,19,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Passes inaccurate,1st half,22-05-2022,La Liga
19,19,20,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Interceptions,1st half,22-05-2022,La Liga

## Remove white spaces from the column `Acciones` (actions)

In [26]:
#TRIM spaces
all_data['Acciones'] = all_data['Acciones'].str.strip()
all_data['Equipos'] = all_data['Equipos'].str.strip()

## Setup columns with the `home team name` and the `away team name`

In [27]:
# Replace score in game description with @
all_data["partido_text"] = all_data["Partido"].replace(to_replace=r'[-]+\d[-]+\d+[-]', value='@', regex=True)

# Create a temp dataframe with columns 'home_team'/'away_team'
localia_df = all_data['partido_text'].str.split('@', expand=True)

# Merge new temp dataframe with all_data dataframe
all_data = pd.concat([all_data, localia_df], axis=1, sort=False)

#Rename new columns
all_data.rename(columns={0: 'equipo_casa', 1: 'equipo_visita'}, inplace=True)
all_data['equipo_casa'] = all_data['equipo_casa'].str.replace(regular_expression, ' ', regex=True)
all_data['equipo_visita'] = all_data['equipo_visita'].str.replace(regular_expression, ' ', regex=True)

#Drop column 'partido_text'
all_data.drop('partido_text', inplace=True, axis=1)

## Preview the dataframe with the new changes

In [28]:
all_data.head(20)

,Unnamed: 0,ID,start,end,code,pos_x,pos_y,Partido,Equipos,Acciones,Tiempo,fecha_partido,nombre_torneo,equipo_casa,equipo_visita
0,0,1,2.29,22.29,10. Iker Muniain,51.8,34.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
1,1,2,2.29,22.29,10. Iker Muniain,51.8,34.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
2,2,3,4.61,24.61,4. Inigo Martinez,33.4,45.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
3,3,4,4.61,24.61,4. Inigo Martinez,33.4,45.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
4,4,5,5.88,25.88,6. Mikel Vesga Arruti,44.9,45.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
5,5,6,5.88,25.88,6. Mikel Vesga Arruti,44.9,45.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
6,6,7,7.49,27.49,4. Inigo Martinez,30.1,46.7,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
7,7,8,7.49,27.49,4. Inigo Martinez,30.1,46.7,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
8,8,9,10.06,30.06,12. Daniel Vivian Moreno,27.3,24.3,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
9,9,10,10.06,30.06,12. Daniel Vivian Moreno,27.3,24.3,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
10,10,11,12.29,13.29,Start,NaN,NaN,Sevilla-1-0-Athletic-Bilbao,NaN,NaN,NaN,22-05-2022,La Liga,Sevilla,Athletic Bilbao
11,11,12,12.38,32.38,18. De Marcos,35.0,4.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
12,12,13,14.07,34.07,18. De Marcos,30.0,4.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
13,13,14,14.07,34.07,18. De Marcos,30.0,4.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
14,14,15,14.81,34.81,12. Daniel Vivian Moreno,22.2,9.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
15,15,16,14.81,34.81,12. Daniel Vivian Moreno,22.2,9.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes inaccurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
16,16,17,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
17,17,18,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
18,18,19,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Passes inaccurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao
19,19,20,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Interceptions,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao

## Get columns for: **`Score`**, **`Home and Away goals`**

In [29]:
# Get the score from column 'Partido' (game)
all_data["marcador"] = all_data['Partido'].str.findall(r'\d[-]+\d+')

#convert column 'marcador' to string
all_data["marcador"] = all_data["marcador"].astype('str') 

# marcador en formato string
all_data["marcador"] = all_data["marcador"].str.slice(start=2, stop=-2)


#New column with the home team goals ('goles_local')
all_data['goles_local'] = all_data["marcador"].str.slice(start=0, stop=1)

#New column with the away team goals ('goles_visita')
all_data['goles_visita'] = all_data["marcador"].str.slice(start=2, stop=3)

## Preview the dataframe with the changes

In [30]:
all_data.head(20)

,Unnamed: 0,ID,start,end,code,pos_x,pos_y,Partido,Equipos,Acciones,Tiempo,fecha_partido,nombre_torneo,equipo_casa,equipo_visita,marcador,goles_local,goles_visita
0,0,1,2.29,22.29,10. Iker Muniain,51.8,34.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
1,1,2,2.29,22.29,10. Iker Muniain,51.8,34.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
2,2,3,4.61,24.61,4. Inigo Martinez,33.4,45.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
3,3,4,4.61,24.61,4. Inigo Martinez,33.4,45.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
4,4,5,5.88,25.88,6. Mikel Vesga Arruti,44.9,45.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
5,5,6,5.88,25.88,6. Mikel Vesga Arruti,44.9,45.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
6,6,7,7.49,27.49,4. Inigo Martinez,30.1,46.7,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
7,7,8,7.49,27.49,4. Inigo Martinez,30.1,46.7,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
8,8,9,10.06,30.06,12. Daniel Vivian Moreno,27.3,24.3,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
9,9,10,10.06,30.06,12. Daniel Vivian Moreno,27.3,24.3,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
10,10,11,12.29,13.29,Start,NaN,NaN,Sevilla-1-0-Athletic-Bilbao,NaN,NaN,NaN,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
11,11,12,12.38,32.38,18. De Marcos,35.0,4.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
12,12,13,14.07,34.07,18. De Marcos,30.0,4.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
13,13,14,14.07,34.07,18. De Marcos,30.0,4.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
14,14,15,14.81,34.81,12. Daniel Vivian Moreno,22.2,9.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
15,15,16,14.81,34.81,12. Daniel Vivian Moreno,22.2,9.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes inaccurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
16,16,17,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
17,17,18,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
18,18,19,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Passes inaccurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0
19,19,20,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Interceptions,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0

## Setup a column with the team that "suffers" the action

In [33]:
# create a list of our conditions

conditions = [
    (all_data["Equipos"] == all_data["equipo_casa"]),
    (all_data["Equipos"] == all_data["equipo_visita"])]

# create a list of the values we want to assign for each condition
values = [all_data["equipo_visita"], all_data["equipo_casa"]]

# create a new column and use np.select to assign values to it using our lists as arguments
all_data["rival"] = np.select(conditions, values)

## Preview the changes

In [34]:
all_data.head(30)

,Unnamed: 0,ID,start,end,code,pos_x,pos_y,Partido,Equipos,Acciones,Tiempo,fecha_partido,nombre_torneo,equipo_casa,equipo_visita,marcador,goles_local,goles_visita,rival
0,0,1,2.29,22.29,10. Iker Muniain,51.8,34.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
1,1,2,2.29,22.29,10. Iker Muniain,51.8,34.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
2,2,3,4.61,24.61,4. Inigo Martinez,33.4,45.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
3,3,4,4.61,24.61,4. Inigo Martinez,33.4,45.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
4,4,5,5.88,25.88,6. Mikel Vesga Arruti,44.9,45.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
5,5,6,5.88,25.88,6. Mikel Vesga Arruti,44.9,45.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
6,6,7,7.49,27.49,4. Inigo Martinez,30.1,46.7,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
7,7,8,7.49,27.49,4. Inigo Martinez,30.1,46.7,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
8,8,9,10.06,30.06,12. Daniel Vivian Moreno,27.3,24.3,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
9,9,10,10.06,30.06,12. Daniel Vivian Moreno,27.3,24.3,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
10,10,11,12.29,13.29,Start,NaN,NaN,Sevilla-1-0-Athletic-Bilbao,NaN,NaN,NaN,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,0
11,11,12,12.38,32.38,18. De Marcos,35.0,4.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
12,12,13,14.07,34.07,18. De Marcos,30.0,4.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
13,13,14,14.07,34.07,18. De Marcos,30.0,4.6,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
14,14,15,14.81,34.81,12. Daniel Vivian Moreno,22.2,9.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
15,15,16,14.81,34.81,12. Daniel Vivian Moreno,22.2,9.9,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes inaccurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
16,16,17,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Athletic Bilbao
17,17,18,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Athletic Bilbao
18,18,19,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Passes inaccurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Athletic Bilbao
19,19,20,17.36,37.36,20. Diego Carlos,32.7,51.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Interceptions,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Athletic Bilbao
20,20,21,18.93,38.93,16. Unai Vencedor Paris,73.8,35.4,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Lost balls,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
21,21,22,18.93,38.93,16. Unai Vencedor Paris,46.7,18.0,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
22,22,23,18.93,38.93,16. Unai Vencedor Paris,46.7,18.0,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Interceptions,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
23,23,24,18.93,38.93,16. Unai Vencedor Paris,46.7,18.0,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
24,24,25,18.93,38.93,16. Unai Vencedor Paris,46.7,18.0,Sevilla-1-0-Athletic-Bilbao,Athletic Bilbao,Passes inaccurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Sevilla
25,25,26,21.42,41.42,23. Jules Kounde,31.2,32.6,Sevilla-1-0-Athletic-Bilbao,Sevilla,Positional attacks,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Athletic Bilbao
26,26,27,21.42,41.42,23. Jules Kounde,31.2,32.6,Sevilla-1-0-Athletic-Bilbao,Sevilla,Pickingups,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Athletic Bilbao
27,27,28,24.09,44.09,23. Jules Kounde,31.7,31.4,Sevilla-1-0-Athletic-Bilbao,Sevilla,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Athletic Bilbao
28,28,29,25.90,45.90,19. Marcos Javier Acuna,30.9,62.9,Sevilla-1-0-Athletic-Bilbao,Sevilla,Passes accurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Athletic Bilbao
29,29,30,28.58,48.58,20. Diego Carlos,19.9,55.1,Sevilla-1-0-Athletic-Bilbao,Sevilla,Passes inaccurate,1st half,22-05-2022,La Liga,Sevilla,Athletic Bilbao,1-0,1,0,Athletic Bilbao

## Remove unnecesary columns

In [ ]:
all_data.drop(all_data.columns[0], axis=1,inplace=True)

## Export the consolidated dataframe to Excel file

In [ ]:

print('Creating excel file with the dataframe all_data')
all_data.to_excel('UNAFUT_'+nombre_torneo+'.xlsx') # YOU CAN SETUP THE FILE NAME THAT YOU WANT
print('done!')

Creating excel file with the dataframe all_data
done!

## Delete all excel files except the file created in the previous step

In [ ]:
print('Detecting all .xlsx files')
excel_files = []
for file in glob.glob("*.xlsx"):
    excel_files.append(file)

print('Removing all excel files except UNAFUT_' + nombre_torneo +'.xlsx')
for file in excel_files:
  if file != ('UNAFUT_' + nombre_torneo + '.xlsx') : # HERE CHANGE AND PUT THE FILE NAME YOU PUT IN THE PREVIOUS STEP
    os.remove(file)

print('All process is done!')

Detecting all .xlsx files
Removing all excel files except UNAFUT_La Liga.xlsx
All process is done!